# nohkwangsun/spark-master-controller.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: subversion
  name: subversion
spec:
  replicas: 1
  selector:
    name: subversion
  template:
    metadata:
      labels:
        name: subversion
    spec:
      containers:
      - image: nohkwangsun/subversion:latest
        name: subversion
        ports:
        - containerPort: 3690
          hostPort: 3690
          protocol: TCP

