apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  ports:
    # the port that this service should serve on
  - name: jdbc
    port: 5432
    targetPort: 5432
  selector:
    name: postgresql

